const sentences = [
  { en: `I once met this Chilean guy at a hostel.`, cn: `我曾经在一家旅舍遇到过一位智利小伙子。` },
  { en: `"So what do you do?"`, cn: `“那么你是做什么的？”` },
  { en: `I asked him.`, cn: `我问他。` },

  { en: `"You mean for work?" he responded as if I had just asked the color of his underwear.`, cn: `他回答：“你是说工作吗？” 好像我刚刚问了他内裤的颜色一样。` },
  { en: `(Laughter)`, cn: `（笑声）` },

  { en: `In the US, "What do you do?" is often the first question we ask when we meet someone new.`, cn: `在美国，“你是做什么的？” 往往是我们遇到新朋友时问的第一个问题。` },
  { en: `This is drilled into us from an early age.`, cn: `这一点从很小的时候就被灌输给我们。` },
  { en: `"What do you want to be when you grow up?" we ask our kids, already conflating who we are with what we do, as if our jobs and identities were one and the same.`, cn: `我们会问孩子：“你长大后想成为什么？” 已经把我们是谁与我们做什么混为一谈，好像我们的工作与我们的身份是同一件事。` },

  { en: `I think about this a lot.`, cn: `我经常想到这件事。` },
  { en: `I'm a labor journalist, and I wrote a book called "The Good Enough Job," in which I spoke to over 100 people about the relationship between their work and their identity.`, cn: `我是一名劳动记者，还写了一本叫《够好工作》的书，在书里我与一百多人谈了他们的工作与身份之间的关系。` },
  { en: `But before I was a professional writer, I was a 22-year-old poetry student trying to figure out what I wanted to be when I grew up.`, cn: `但在我成为一名职业作家之前，我是一个二十二岁的诗歌专业学生，正试图弄清楚自己长大后想成为什么。` },
  { en: `It was around this time that I had the opportunity to interview my favorite writer in the entire world, the poet Anis Mojgani.`, cn: `就在这段时间里，我有机会采访到全世界我最喜欢的作家——诗人 Anis Mojgani。` },
  { en: `And so I asked him, "Anis, how do you feel about the mantra, do what you love and never work a day in your life?"`, cn: `于是我问他：“Anis，你如何看待那句箴言——做你所爱，这样你一辈子都不用工作？”` },

  { en: `And I'll never forget what he told me.`, cn: `我永远不会忘记他对我说的话。` },
  { en: `He said, "You know, Simone, I think some people do what they love for work, and others do what they have to so they can do what they love when they're not working.`, cn: `他说：“你知道吗，Simone，我认为有些人把自己所爱之事当作工作，而另一些人做他们必须做的事，好让他们在不工作时能够去做他们所爱。` },
  { en: `And neither is more noble."`, cn: `而这两者并没有谁更高贵。”` },

  { en: `I think that last part is key.`, cn: `我认为最后那部分是关键。` },
  { en: `We live in a society that loves to revere people whose jobs and identities neatly align.`, cn: `我们生活在一个喜欢崇敬那些工作与身份整齐对齐的人的社会里。` },
  { en: `And here was my idol, a professional poet no less, telling me that it's OK to have a day job.`, cn: `而我的偶像——而且还是一位职业诗人——在告诉我，有一份日常工作是没问题的。` },
  { en: `If we want to develop a healthier relationship to work, we can't just think about work-life balance in terms of how we spend our time.`, cn: `如果我们想与工作建立更健康的关系，我们就不能只从时间如何分配的角度来思考工作与生活的平衡。` },
  { en: `We have to think about how we construct our identity.`, cn: `我们必须思考我们怎样建构自己的身份。` },
  { en: `What we do is part of but not the entirety of who we are.`, cn: `我们做什么只是我们是谁的一部分，而不是我们的全部。` },

  { en: `Let me be clear.`, cn: `让我说明白。` },
  { en: `I don't think there's anything wrong with doing what you love for work.`, cn: `我不认为把你所爱之事当作工作有什么不对。` },
  { en: `We work more than we do just about anything else, and how we spend those hours matters.`, cn: `我们把大量时间用于工作，超过几乎一切其他事情，而我们如何度过这些小时很重要。` },
  { en: `And yet, our current relationship to work isn't quite working.`, cn: `然而，我们当前与工作的关系并不太奏效。` },
  { en: `A recent study found that 48 percent of workers around the globe are burnt out.`, cn: `一项最新研究发现，全球有 48% 的劳动者处于精疲力竭状态。` },
  { en: `48 percent.`, cn: `48%。` },
  { en: `That's half this room.`, cn: `那是这个房间的一半人。` },
  { en: `Actually, in this room, probably more than half.`, cn: `事实上，就在这个房间里，可能还不止一半。` },
  { en: `And yet, the way that we commonly talk about burnout doesn't address its root cause.`, cn: `然而，我们通常谈论倦怠的方式并没有触及其根本原因。` },
  { en: `There's a reason why a one-week vacation doesn't magically cure us.`, cn: `之所以一个为期一周的假期不能神奇地治愈我们，是有原因的。` },
  { en: `There's a reason why our intentions to practice self-care and set better boundaries inevitably break down.`, cn: `之所以我们打算进行自我关照和设定更好边界的努力不可避免地崩溃，也是有原因的。` },
  { en: `It's like we're shielding ourselves from the sun with a cocktail umbrella.`, cn: `这就好像我们正用一把鸡尾酒小伞来挡太阳。` },
  { en: `If we want to actually change our relationship to work, we have to go deeper.`, cn: `如果我们真的想改变与工作的关系，我们必须走得更深。` },
  { en: `It starts with our identity.`, cn: `这要从我们的身份开始。` },

  { en: `Certainly, we are all more than just workers.`, cn: `当然，我们都不仅仅是劳动者。` },
  { en: `We’re parents and friends and citizens and artists and travelers and neighbors.`, cn: `我们还是父母、朋友、公民、艺术家、旅行者以及邻居。` },
  { en: `Much like an investor benefits from diversifying the sources of stocks in their portfolio, we, too, benefit from diversifying the sources of meaning and identity in our lives.`, cn: `就像投资者从其投资组合中分散股票来源而获益一样，我们也能从在生活中分散意义与身份的来源而获益。` },
  { en: `But how do you actually go about doing so?`, cn: `但你究竟要如何实际去做呢？` },

  { en: `Rabbi Abraham Joshua Heschel described Shabbat, the weekly Jewish practice of abstaining from work, as a sanctuary in time.`, cn: `拉比 Abraham Joshua Heschel 将“安息日”——犹太人每周禁工的做法——描述为“时间中的圣所”。` },
  { en: `I love this image.`, cn: `我喜欢这个意象。` },
  { en: `Rather than a physical sanctuary, like a synagogue, Shabbat is a time sanctuary.`, cn: `与其说是一座实体的圣所（如犹太会堂），不如说安息日是一处“时间的圣所”。` },

  { en: `So the first step to diversifying your identity is to create those time sanctuaries, spaces in your days, in your weeks, in your life where work is not an option.`, cn: `因此，多元化你身份的第一步是创造那些“时间圣所”——在你的一天、一周与一生中让工作不再成为选项的空间。` },
  { en: `Unlike mere intentions to work less or set better boundaries, time sanctuaries require infrastructure.`, cn: `不同于仅仅打算少工作或设定更好边界，“时间圣所”需要基础设施。` },
  { en: `Putting time on the calendar to learn a new language, putting your phone in airplane mode while you play with your kids so that work doesn't expand like a gas and fill all of your unoccupied space.`, cn: `把学习一门新语言的时间写进日程，在你和孩子玩耍时把手机调为飞行模式，这样工作就不会像气体那样膨胀并填满你所有未被占据的空间。` },

  { en: `The second step is to fill those time sanctuaries with activities that reinforce the other identities you hope to cultivate.`, cn: `第二步是用那些能强化你希望培养的其他身份的活动来填满这些“时间圣所”。` },
  { en: `The present father, the community gardener, the amateur musician.`, cn: `比如当下投入的父亲、社区的园丁、业余的音乐人。` },
  { en: `It may sound simple, but if we want to derive meaning from aspects of our life other than work, we have to do things other than work.`, cn: `这听起来可能很简单，但如果我们想从工作之外的生活侧面获得意义，我们就必须去做工作之外的事情。` },
  { en: `Now these don't have to be grand gestures.`, cn: `而这些不必是宏大的举动。` },
  { en: `In the reporting in my book, I spoke to all of these hyperambitious workaholics, and they'd say things like, "Diversify my identity.`, cn: `在我的书的报道中，我与那些极度雄心勃勃的工作狂交谈，他们会说类似的话：“多元化我的身份。` },
  { en: `Got it.`, cn: `明白了。` },
  { en: `I’m going to read 52 books this year.`, cn: `我今年要读 52 本书。` },
  { en: `Or I’m going to run an ultramarathon.”`, cn: `或者我要去跑一场超级马拉松。”` },
  { en: `We even convert our leisure into other forms of labor.`, cn: `我们甚至把我们的休闲转化成了其他形式的劳动。` },
  { en: `My advice is to start small.`, cn: `我的建议是从小处开始。` },
  { en: `How about a weekly walk with your best friend?`, cn: `比如每周与最好的朋友散步一次如何？` },
  { en: `Or ten minutes practicing the piano after dinner.`, cn: `或者晚饭后练十分钟钢琴。` },

  { en: `The third step is to reinforce these identities by joining communities who couldn't care less about what you do for work.`, cn: `第三步是通过加入那些并不在乎你做什么工作的人群体来强化这些身份。` },
  { en: `For example, I love to play pickup basketball, and one of the benefits of my weekly game is that the people I play with don't care how many words I've written or how many books I've sold.`, cn: `例如，我喜欢打野球，而我每周打球的一个好处是，和我一起打的人并不关心我写了多少字或卖出了多少本书。` },
  { en: `They care that I show up on time and that I'm a good teammate.`, cn: `他们在意的是我是否按时出现，以及我是不是个好队友。` },
  { en: `It’s a weekly reminder that I exist on this Earth to do more than just produce economic value.`, cn: `这每周都提醒我：我存在于这个世界并不只是为了产出经济价值。` },
  { en: `The irony is that diversifying our identity can be great for business too.`, cn: `具有讽刺意味的是，多元化我们的身份对事业也很有好处。` },
  { en: `Research shows that people with varied interests tend to be more creative problem solvers and more innovative.`, cn: `研究显示，拥有多样兴趣的人往往是更有创造力的问题解决者，也更具创新性。` },
  { en: `Hobbies are one of the best ways to recharge so that you can be more productive when you're back on the clock.`, cn: `爱好是为自己充电的最佳方式之一，这样当你回到工作时会更有效率。` },
  { en: `And a diverse identity can come in handy in the face of a stressful event like a recession or a layoff.`, cn: `而在面对经济衰退或裁员等压力事件时，多元的身份也能派上用场。` },
  { en: `I spoke to all of these folks for my book who treated their work like their family and then were unceremoniously let go during the pandemic.`, cn: `我在书中采访了那些把工作当作家庭的人，而他们在疫情期间却被毫不客气地解雇。` },
  { en: `If you are what you do and you lose your job, who are you?`, cn: `如果你就是你的工作，而你失去了工作，那么你是谁？` },

  { en: `But in addition to the business case, there's also the moral case.`, cn: `但除了事业层面的理由之外，还有道德层面的理由。` },
  { en: `If we want to develop more well-rounded versions of ourselves, if we want to build robust relationships and live in robust communities and have a robust society at large, we all must invest in aspects of our lives beyond work.`, cn: `如果我们想把自己发展得更全面，如果我们想建立稳固的关系、生活在稳固的社区并拥有总体稳固的社会，我们就必须在工作之外的生活方面投入。` },
  { en: `We shouldn't just work less because it makes us better workers.`, cn: `我们不应仅仅因为少工作会让我们成为更好的劳动者而去少工作。` },
  { en: `We should work less because it makes us better people.`, cn: `我们应该少工作，因为这会让我们成为更好的人。` },
  { en: `This isn't just about you and me.`, cn: `这不仅仅关乎你和我。` },
  { en: `This is about teaching our kids that their self-worth is not determined by their job title.`, cn: `这关乎教导我们的孩子：他们的自我价值并不由他们的职位头衔决定。` },
  { en: `This is about reinforcing the fact that not all noble work neatly translates to a line on a resume.`, cn: `这关乎强化这样一个事实：并非所有高尚的工作都能整齐地转化为简历上的一行字。` },
  { en: `This is about setting the example that we all have a responsibility to contribute to the world in a way beyond contributing to one organization's bottom line.`, cn: `这关乎树立一个榜样：我们都有责任以超越为某个组织利润做贡献的方式来为世界作出贡献。` },

  { en: `So the next time you're at a party, instead of asking someone, "What do you do?" I encourage you to add two small words to your question.`, cn: `因此，下次你在聚会上，与其问别人“你是做什么的？”，我鼓励你在问题里加上两个小词。` },
  { en: `Instead, ask them, "What do you like to do?"`, cn: `换句话说，问他们：“你喜欢做什么？”` },
  { en: `Maybe you like to cook.`, cn: `也许你喜欢做饭。` },
  { en: `Maybe you like to write.`, cn: `也许你喜欢写作。` },
  { en: `Maybe you do some of those things for work.`, cn: `也许你把其中的一些事当作工作来做。` },
  { en: `Or maybe you don't.`, cn: `或者也许你并没有。` },
  { en: `But "What do you like to do" is a question that allows each of us to define ourselves on our own terms.`, cn: `但“你喜欢做什么”这个问题允许我们每个人用自己的方式来定义自己。` },

  { en: `Thank you.`, cn: `谢谢。` },
  { en: `(Applause)`, cn: `（掌声）` }
];
